#!/bin/sh
# Commented this for lab5
# Enter a grocery list and
# COMMENT
# store in a file indicated by $1
echo To end list, enter \"all\".
item=nothing
until test $item = "all"
do
        echo "Enter grocery item: "
        read item
        echo $item >> $1
done
